# .github/workflows/test-secret.yml

name: Test Secret Usage

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests with secret
        shell: bash
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "Running tests with secret"
          bash eval/run_tests.sh "$TEST_SECRET"
